In [1]:
import numpy as np
import pandas as pd
import nltk
from collections import Counter 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import matplotlib.pyplot as plt
from zipfile import ZipFile 
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest, chi2
import pickle

In [2]:
corpus = pd.read_csv("C:/Users/User/Downloads/TA/traindata.csv")
corpus.head()

review  label
0                                      starter gituu      0
1  motor matic xeon karbu kemarin mati starter ak...      0
2  saring filter karbu tenaga saring tenaga gas s...      1
3  honda matic vario esp habis oli mesin karna tu...      1
4                                              mesin      1

In [3]:
corpus.shape

(404, 2)

In [4]:
corpus_test = pd.read_csv("C:/Users/User/Downloads/TA/testdata.csv")
corpus_test.head()

review  label
0                      motor mio sporty setang getar      0
1                     maaf mesin motor honda beat fi      1
2                   kabel spul mio soul api warna om      0
3  motor karisma lampu papan monitor tanda sen la...      0
4           speedo meter mati indikator bensin ganti      0

In [5]:
vectorizer = CountVectorizer(ngram_range=(2,3)).fit(corpus['review'])
X = vectorizer.transform(corpus['review'])
print (X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
X_test = vectorizer.transform(corpus_test['review'])
print (X_test.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True).fit(X)
X = tfidf_transformer.transform(X)
print (X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
X_test = tfidf_transformer.transform(X_test)
print (X_test.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
X_test.shape

(101, 4335)

In [10]:
y= corpus['label'].values
print(y)

[0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 0
 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1
 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1
 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 0 0 1
 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 1 0 1 1
 1 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 1 1 0
 1 1 1 0 0 1 0 1 1 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 0
 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0
 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 0]


In [11]:
y_test= corpus_test['label'].values
print(y_test)

[0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 1 1 1 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 1
 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 0]


In [12]:
filename = 'xy23.p'
outfile = open(filename,'wb')
pickle.dump([X,y],outfile)
outfile.close()

In [13]:
filename = 'xy_test23.p'
outfile = open(filename,'wb')
pickle.dump([X_test,y_test],outfile)
outfile.close()

In [14]:
# print idf values
#df_idf = pd.DataFrame(tfidf_transformer.idf_, index=vectorizer.get_feature_names(),columns=["idf_weights"])
 
# sort ascending
#df_idf.sort_values(by=['idf_weights'])

In [15]:
#fitur = vectorizer.get_feature_names()
#fitur